apriltag:
  ros__parameters:
    size: 0.2
    detector:
      threads: 2
lab3_node:
  ros__parameters:
    map:
      - -1.5
      - 0.125
      - -3.0
      - 0.125
      - 0.5
      - 0.125
      - 2.1
      - -4.0
      - 0.5
      - -5.72
      - -3.46
      - -4.0
      - -2.0
      - -2.03
      - -7.3
      - 5.72
      - -7.4
      - -5.72
      - 4.0
      - -1.87
      - 10.0
      - -1.87
      - -5.65
      - 3.0
      - -5.75
      - -4.0
      - 14.05
      - -1.0
      - 14.05
      - 2.5
      - -8.85
      - 4.0
      - -9.95
      - -0.5
      - -8.85
      - -4.0
